# Redis RDB persistence configuration

# Save RDB snapshot when at least 1 key changed in 3600s
save 3600 1
# More aggressive defaults:
save 900 1
save 60 10000

# Compress RDB files
rdbcompression yes
rdbchecksum yes

# Disable AOF (RDB is sufficient for failed IDs)
appendonly no

# Where to store the RDB file
dir /data
dbfilename dump.rdb
